version: "3.3"
services:
  db:
    image: postgres:11.1
    env_file:
      - ./env/dev.env
    ports:
      - "5434:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    tty: true
    restart: always
    build: ./backend
    env_file:
      - ./env/dev.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - staticfiles:/static

  frontend:
    restart: always
    build: ./frontend
    command: npm start
    env_file:
      - ./env/dev.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend-modules:/app/node_modules

volumes:
  pg-data:
    driver: local

  frontend-modules:
    driver: local

  staticfiles:
    driver: local
